name: react workflow 
on: push
jobs:
  first_job:
    runs-on: ubuntu:latest
    steps:
      - name: Code checkout
        uses: actions/chekcout@v4
      - name: install nodejs22
        uses: actions/steup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: npm test
        run: npm test

